---
# tasks/configure.yml - Configure Certbot

- name: Create Certbot configuration directory
  ansible.builtin.file:
    path: "{{ certbot_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Create Certbot work directory
  ansible.builtin.file:
    path: "{{ certbot_work_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Create Certbot logs directory
  ansible.builtin.file:
    path: "{{ certbot_logs_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Create renewal hooks directories
  ansible.builtin.file:
    path: "{{ certbot_config_dir }}/renewal-hooks/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  with_items:
    - pre
    - post
    - deploy
  become: true

- name: Create deploy script if provided
  ansible.builtin.template:
    src: renewal-hooks/post/deploy.sh.j2
    dest: "{{ certbot_config_dir }}/renewal-hooks/post/{{ item.name }}"
    owner: root
    group: root
    mode: '0755'
  with_items: "{{ certbot_post_hooks }}"
  when: certbot_post_hooks is defined
  become: true